# Generated by Django 2.0.10 on 2019-03-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190131_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_duration',
            field=models.IntegerField(),
        ),
    ]
