# Generated by Django 2.1.4 on 2019-01-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190114_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(choices=[('1', 'First Year Undergrad'), ('2', 'Second Year Undergrad'), ('3', 'Third Year Undergrad'), ('4', 'Fourth Year Undergrad'), ('5', 'Postgrads (5th year DD, PG+))')], max_length=1),
        ),
    ]
