# Generated by Django 2.0.10 on 2019-03-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190305_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
