# Generated by Django 2.1.4 on 2019-01-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190131_1536'),
        ('users', '0004_auto_20190114_1623'),
    ]

    operations = [
    ]
