# Generated by Django 2.1.4 on 2019-01-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190116_1015'),
        ('users', '0004_auto_20190114_1623'),
    ]

    operations = [
    ]
