# Generated by Django 2.1.4 on 2019-01-31 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20190131_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skill', models.CharField(max_length=50)),
                ('job_start_date', models.DateField()),
                ('job_duration', models.CharField(max_length=255)),
                ('stipend', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Company')),
            ],
        ),
    ]
