# Generated by Django 2.1.4 on 2019-01-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
