# Generated by Django 2.1.7 on 2019-02-23 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20190114_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('I', 'Internship'), ('P', 'Project')], max_length=1)),
                ('description', models.CharField(max_length=10000)),
                ('duration', models.CharField(max_length=20)),
                ('pay', models.CharField(max_length=10)),
                ('vacancies', models.PositiveIntegerField()),
                ('apply_by', models.DateField()),
                ('start_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.Company')),
            ],
        ),
    ]
